SET(IMGUI_LIBRARIES ${CMAKE_SOURCE_DIR}/libs/libimgui.so)

IF (EXISTS "${IMGUI_LIBRARIES}")
    MESSAGE(STATUS "Found ImGUI: ${IMGUI_LIBRARIES}")
ELSE ()
    MESSAGE(FATAL_ERROR "ImGUI not found: ${IMGUI_LIBRARIES}")
ENDIF ()

SET(IMGUI_INCLUDE_DIRS ${CMAKE_SOURCE_DIR}/libs/include/)
IF (EXISTS ${IMGUI_INCLUDE_DIRS})
ELSE ()
    MESSAGE(FATAL_ERROR "include for ImGUI invalid or not found: ${IMGUI_INCLUDE_DIRS}")
ENDIF ()
